CREATE TABLE country
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30),
	Code INTEGER,
	Discription CHARACTER VARYING(30)
);

CREATE TABLE city
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30),
	Code INTEGER,
	Id uuid,
	Discription CHARACTER VARYING(30)
);

CREATE TABLE Citizen
(
	Id SERIAL PRIMARY KEY,
	FirstName CHARACTER VARYING(30),
	LastName CHARACTER VARYING(30),
	Birthday INTEGER,
	City_id uuid
);
